markdown: kramdown
url: ''
baseurl: null
title: Hey! I'm Chrisma
site-image: /WhatATheme/assets/images/meta.jpg
site-keywords: 'Site, Template, Theme'
favicon-url: null
heroimage: >- https://lh3.googleusercontent.com/v6DaUFA_KlmnNXUj4dzHGzGMlMsnKRW9qn6C9E1dKMr7otKa6YVAENDGqL6xybAJndyTIhnJcp8HTkuZDI_5Ve14t0S5YzgASEluqg6oKerJftKJBzrh0JP4bqgb1Hu_PKDRs7G-fNOgXQzuL99isJ_o7a67y_KbNTjiPy96bZA3KBXmkfVDFOSwtd2K6zIoAlkVy4Ucg7h9Kkp-ru2yyUFR6wGueaTC8LsoCnnSC4jT7ryDyRWh2T0FkTD0CibWorEYiD8Op2im0FxQoIr1cwiS1fw_QdLCpffLVcK6e09nEjvbi01eRNUnRNYr_DH6ighS3_j4sIcZCw_hEaXXrpSIhh2D08iCsNIFZgZFa4vIFtrcTP3iyPgObTCNTik68osPfLKESK7HK7g4U5SuGYkOtvFvHw66mTJYFPh9AccBo2VLePjNTtdtBJm-JlStNabNx2VoeXotWO5fENQc2Nyi9rap4NpDF4WOhEJS0REVkUcXL8TxwmXEs82ZM6fI5uKysei7i6FghG7P9gaQxjcDnz8-13pDiZ4ufJTVDVX1z_38tUpAH_TPsxRPOWrlDbm21edaV5eOtFQaec3aFiKnfo6ivb0rpUPJaVeONn-JWDJO-vBXpBsO_I-LBBuSqQGcBvQdWuAelbI5-QeGidTQrhzGJJxpjk5ZBq0iq-F9a0qSBy7GxPMxqp_7hMqD_FPh6VZBF1IQNnm7AKPfSCg=w703-h937-no?authuser=0
email: claredsouza27@gmail.com
twitter_username: chrismadsouza
instagram_username: chrismadsouza
linkedin_username: chrisma-d-souza-158493142
github_username: chrismadsouza
youtube_channel_id: UCjlzEHGH1VDKCGE_zh-YAow
disqus-shortname: chrisma
author-name: Chrisma Clare D'Souza
author-image: >- /WhatATheme/Capture.PNG
author-about: >-
  I'm a Research Assistant working under Prof. Aaditya Dar at the Indian School
  of Business in projects of development economics. I'm very interested in the
  applications of data science in the field of developmental economics.  I love
  travelling, trekking, playing the piano, watching the sun set at beaches,
  reading a book on a rainy day, developmental economics, nature, astronomy,
  desserts and this adventurous short stint called life.
author-url: 'https://github.com/chrismadsouza'
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-admin
  - jekyll-feed
permalink: 'blog/:title'
compress_html:
  clippings: all
defaults:
  - scope:
      type: posts
    values:
      layout: post
      post-image: ''
      description: ''
      tags:
        - ''
  - scope:
      type: pages
    values:
      layout: page
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
